Repository jetstack/spiffe-connector, pull requests merged in 2022-05, with the labels that each got.

#20 Add goreleaser token to github action workflow
  .github/workflows/goreleaser.yaml
Labels: size/XS

#22 Fix demos on my machine
  deploy/02-csi-driver-spiffe.yaml
  hack/demo.sh
Labels: size/XS

#23 Demo fixes
  .gitignore
  .goreleaser.demo.arm64.yaml
  deploy/07-example-app.yaml
Labels: size/M

#24 securityContext fixes in demo
  deploy/06-spiffe-connector-server.yaml
  deploy/07-example-app.yaml
Labels: size/XS

#25 Demo Updates
  .goreleaser.demo.yaml
  deploy/06-spiffe-connector-server.yaml
  deploy/07-example-app.yaml
  example/go.mod
  example/go.sum
  example/internal/cmd/server/cmd.go
  example/internal/cmd/server/main.go
  example/internal/pkg/handlers/css/normalize.min.css
  example/internal/pkg/handlers/css/styles.css
  example/internal/pkg/handlers/css/tachyons.min.css
  example/internal/pkg/handlers/index.go
  example/internal/pkg/handlers/index.html
  example/internal/pkg/handlers/move.go
  example/internal/pkg/handlers/styles.go
  example/main.go
  hack/demo.sh
Labels: size/XL
